### ISSUE TITLE
Why the package thormang3_navigation is ignored in CATKIN?

### ISSUE THREAD

**Issue by whtqh** [thor-mang/thor_mang_install#1]
~~## ROBOTIS Package failed in catkin_make~~
~~Origin package in ROBOTIS-THORMANG3 can not be built successfully for the footstep_planner failure.~~
What the hell! the problem solved just by add thormang3_footstep_planner.launch and other files into /humanoid_navigation 's footstep planner.
## CATKIN_IGNORE path planning
There is a CATKIN_IGNORE in Hector's package, ~~but how to realize a path planning in simulation?~~ Maybe the hector's team has a better path planner :+1:

**Comment by astumpf** [comment]
Hello,

Indeed, we are using a "better path planner". Our internal thormang3 setup uses the ViGIR footstep planning framework (see http://wiki.ros.org/vigir_footstep_planning).
If you are using our workspace setup, then I would like to recommend reading the subsection "THORMANG3 Demo" (http://wiki.ros.org/vigir_footstep_planning#thormang3_demo). We provide a ready-to-use setup.

If you are **not** using our workspace setup, then you must merge the rosinstalls _ui_ and _footstep_planning_ from here: https://github.com/thor-mang/thor_mang_install/tree/kinetic-devel/rosinstall/optional (using _wstool merge_ command). However, you would also require to use our version of the _thormang3_manager_ from here: https://github.com/thor-mang/ROBOTIS-THORMANG-MPC. In particular, the only change should be adding our _thormang3_step_control_module_ to the _thormang3_manager_ in order to run our footstep planning solution.

Best,
Alex
